#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'logger'
require 'optparse'
require 'unitf/tag'
require 'unitf/logging'

UnitF::Log.to_console

files = UnitF::Tag::FileSet.new(ARGV)

files.each do |file|
  puts "File: #{file}"
  puts "Tags: #{file.auto_tags}"
end
